<map version="1.0.1">
<!-- To view this file, download free mind mapping software FreeMind from http://freemind.sourceforge.net -->
<node CREATED="1615569313729" ID="ID_740307475" MODIFIED="1615569317931" TEXT="Ruby">
<node CREATED="1615570727581" ID="ID_898111510" MODIFIED="1615570733742" POSITION="left" TEXT="paradigms">
<node CREATED="1615570735066" ID="ID_312967657" MODIFIED="1615570737795" TEXT="functinoal"/>
<node CREATED="1615570738393" ID="ID_4980211" MODIFIED="1615570743714" TEXT="imperative"/>
<node CREATED="1615570749718" ID="ID_1200720245" MODIFIED="1615570765864" TEXT="object-oriented"/>
<node CREATED="1615570758752" ID="ID_94780183" MODIFIED="1615570761059" TEXT="reflective"/>
</node>
<node CREATED="1615570776256" ID="ID_972300389" MODIFIED="1615570778596" POSITION="left" TEXT="tools">
<node CREATED="1615569637048" ID="ID_237863346" MODIFIED="1615569875021" TEXT="rbenv">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      https://github.com/rbenv/rbenv#readme
    </p>
    <p>
      
    </p>
    <p>
      <a http-equiv="content-type" content="text/html; charset=utf-8" href="https://github.com/rbenv/rbenv#readme" style="background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; background-position: null; color: rgb(68, 84, 136); text-decoration: underline; font-family: Noto Sans, Helvetica Neue, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-weight: 400; letter-spacing: normal; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px"><font color="rgb(68, 84, 136)" face="Noto Sans, Helvetica Neue, Helvetica, sans-serif" size="16px"><u>rbenv</u></font></a><font color="rgb(17, 17, 17)" face="Noto Sans, Helvetica Neue, Helvetica, sans-serif">&#160;allows you to manage multiple installations of Ruby. While it can&#8217;t install Ruby by default, its&#160;</font><a href="https://www.ruby-lang.org/en/documentation/installation/#ruby-build" style="background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; background-position: null; color: rgb(68, 84, 136); text-decoration: underline; font-family: Noto Sans, Helvetica Neue, Helvetica, sans-serif; font-size: 16px; font-style: normal; font-weight: 400; letter-spacing: normal; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; word-spacing: 0px"><font color="rgb(68, 84, 136)" face="Noto Sans, Helvetica Neue, Helvetica, sans-serif" size="16px"><u>ruby-build</u></font></a><font color="rgb(17, 17, 17)" face="Noto Sans, Helvetica Neue, Helvetica, sans-serif">&#160;plugin can. Both tools are available for macOS, Linux, or other UNIX-like operating systems. </font>
    </p>
    <p>
      Put rbenv to work with Bundler for painless Ruby upgrades and bulletproof deployments.
    </p>
  </body>
</html></richcontent>
</node>
<node CREATED="1615578634036" ID="ID_1423658858" MODIFIED="1615578639811" TEXT="Bundler">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      https://bundler.io/
    </p>
  </body>
</html></richcontent>
</node>
</node>
<node CREATED="1615583759554" ID="ID_1925909929" MODIFIED="1615583769009" POSITION="right" TEXT="irb"/>
<node CREATED="1615577203989" ID="ID_332981954" MODIFIED="1615577224332" POSITION="right" TEXT="comment">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      # comment
    </p>
  </body>
</html></richcontent>
</node>
<node CREATED="1615576685173" ID="ID_849430151" MODIFIED="1615576750189" POSITION="right" TEXT="data structures">
<node CREATED="1615576724928" ID="ID_1429481832" MODIFIED="1615576727396" TEXT="nil"/>
</node>
<node CREATED="1615575293528" ID="ID_1414184314" MODIFIED="1615575622547" POSITION="right" TEXT="function">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      def hi (name)
    </p>
    <p>
      &#160;&#160;&#160;&#160;puts &quot;Hello #{name}!&quot;
    </p>
    <p>
      end
    </p>
    <p>
      
    </p>
    <p>
      def hi (name =&quot;World&quot;)
    </p>
    <p>
      &#160;&#160;&#160;&#160;puts &quot;Hello #{name.capitalize}!&quot;
    </p>
    <p>
      end
    </p>
  </body>
</html></richcontent>
<node CREATED="1617129277012" ID="ID_1190532626" MODIFIED="1620151236167" TEXT="opts">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      Ruby does not support overloading of functions.
    </p>
    <p>
      You can use opts = {} as an input parameter and check wether some opts are given to support variable input parameter.
    </p>
    <p>
      
    </p>
    <p>
      def foo(param1, opts = {})
    </p>
    <p>
      &#160;&#160;if opts.extra? :extra
    </p>
    <p>
      
    </p>
    <p>
      foo(one, {extra: bar})
    </p>
  </body>
</html>
</richcontent>
</node>
</node>
<node CREATED="1615575613859" ID="ID_716781441" MODIFIED="1615576703176" POSITION="right" TEXT="class">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      class Greeter
    </p>
    <p>
      &#160;&#160;&#160;&#160;def initialize (name = &quot;World&quot;)
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;@name = name
    </p>
    <p>
      &#160;&#160;&#160;&#160;end
    </p>
    <p>
      &#160;&#160;&#160;&#160;def say_hi
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;puts &quot;Hi #{@name}!&quot;
    </p>
    <p>
      &#160;&#160;&#160;&#160;end
    </p>
    <p>
      &#160;&#160;&#160;&#160;def say_bye
    </p>
    <p>
      &#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;puts &quot;Bye #{@name}, come back soon!&quot;
    </p>
    <p>
      &#160;&#160;&#160;&#160;end
    </p>
    <p>
      end
    </p>
    <p>
      
    </p>
    <p>
      ---
    </p>
    <p>
      
    </p>
    <p>
      Greeter.new(&quot;Alice&quot;)
    </p>
    <p>
      
    </p>
    <p>
      ---
    </p>
    <p>
      
    </p>
    <p>
      Getter/Setter
    </p>
    <p>
      
    </p>
    <p>
      class Greeter
    </p>
    <p>
      &#160;&#160;&#160;&#160;attr_accessor :name
    </p>
    <p>
      end
    </p>
    <p>
      
    </p>
    <p>
      greeter = Greeter.new(&quot;Alice&quot;)
    </p>
    <p>
      greeter.name
    </p>
    <p>
      &gt; Alice
    </p>
    <p>
      greeter.name=&quot;Bob&quot;
    </p>
    <p>
      greeter.name
    </p>
    <p>
      &gt; Bob
    </p>
  </body>
</html></richcontent>
</node>
<node CREATED="1615576708687" ID="ID_175911820" MODIFIED="1615576753341" POSITION="right" TEXT="control structures">
<node CREATED="1615576756383" ID="ID_1740506593" MODIFIED="1615577006794" TEXT="condition">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      if @name.nil?
    </p>
    <p>
      &#160;&#160;&#160;&#160;...
    </p>
    <p>
      elsif @name = &quot;Bob&quot;
    </p>
    <p>
      &#160;&#160;&#160;&#160;...
    </p>
    <p>
      else
    </p>
    <p>
      &#160;&#160;&#160;&#160;...
    </p>
    <p>
      end
    </p>
  </body>
</html></richcontent>
</node>
<node CREATED="1615577008088" ID="ID_1568460740" MODIFIED="1615577043950" TEXT="loop">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <p>
      @names.each do |name|
    </p>
    <p>
      &#160;&#160;&#160;&#160;puts &quot;Hello #{name}!&quot;
    </p>
    <p>
      end
    </p>
  </body>
</html></richcontent>
</node>
</node>
<node CREATED="1617128297781" ID="ID_867891756" MODIFIED="1617129261890" POSITION="right" TEXT="mixin">
<richcontent TYPE="NOTE"><html>
  <head>
    
  </head>
  <body>
    <div http-equiv="content-type" content="text/html; charset=utf-8" class="line number1 index0 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="comments" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 130, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="#000000">Ruby does not support multi-inheritence. But you can use mixins to include functionallity of multiple modules.</font><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 130, 0) !important"> # Ruby program of mixins</font></code>
    </div>
    <div class="line number2 index1 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;</font></code>&#160;
    </div>
    <div class="line number3 index2 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="comments" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 130, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 130, 0) !important"># module consist 2 methods</font></code>
    </div>
    <div class="line number4 index3 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">module</font></code>&#160;<code class="constants" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 204) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 204) !important">G</font></code>
    </div>
    <div class="line number5 index4 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;&#160;&#160;&#160;</font></code><code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">def</font></code>&#160;<code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">g1</font></code>
    </div>
    <div class="line number6 index5 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;&#160;&#160;</font></code><code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">end</font></code>
    </div>
    <div class="line number7 index6 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;&#160;&#160;</font></code><code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">def</font></code>&#160;<code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">g2</font></code>
    </div>
    <div class="line number8 index7 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;&#160;&#160;</font></code><code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">end</font></code>
    </div>
    <div class="line number9 index8 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">end</font></code>
    </div>
    <div class="line number10 index9 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;</font></code>&#160;
    </div>
    <div class="line number11 index10 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="comments" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 130, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 130, 0) !important"># module consist 2 methods</font></code>
    </div>
    <div class="line number12 index11 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">module</font></code>&#160;<code class="constants" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 204) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 204) !important">GFG</font></code>
    </div>
    <div class="line number13 index12 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;&#160;&#160;</font></code><code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">def</font></code>&#160;<code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">gfg1</font></code>
    </div>
    <div class="line number14 index13 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;&#160;&#160;</font></code><code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">end</font></code>
    </div>
    <div class="line number15 index14 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;&#160;&#160;</font></code><code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">def</font></code>&#160;<code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">gfg2</font></code>
    </div>
    <div class="line number16 index15 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;&#160;&#160;</font></code><code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">end</font></code>
    </div>
    <div class="line number17 index16 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">end</font></code>
    </div>
    <div class="line number18 index17 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;</font></code>&#160;
    </div>
    <div class="line number19 index18 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="comments" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 130, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 130, 0) !important"># Creating a class</font></code>
    </div>
    <div class="line number20 index19 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">class</font></code>&#160;<code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">GeeksforGeeks</font></code>
    </div>
    <div class="line number21 index20 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">include </font></code><code class="constants" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 204) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 204) !important">G</font></code>
    </div>
    <div class="line number22 index21 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">include </font></code><code class="constants" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 204) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 204) !important">GFG</font></code>
    </div>
    <div class="line number23 index22 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;&#160;&#160;</font></code><code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">def</font></code>&#160;<code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">s1</font></code>
    </div>
    <div class="line number24 index23 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;&#160;&#160;</font></code><code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">end</font></code>
    </div>
    <div class="line number25 index24 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">end</font></code>
    </div>
    <div class="line number26 index25 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;</font></code>&#160;
    </div>
    <div class="line number27 index26 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="comments" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 130, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 130, 0) !important"># Creating object</font></code>
    </div>
    <div class="line number28 index27 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">gfg = GeeksforGeeks.</font></code><code class="keyword" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 102, 153) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 102, 153) !important">new</font></code>
    </div>
    <div class="line number29 index28 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="undefined spaces" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important">&#160;</font></code>&#160;
    </div>
    <div class="line number30 index29 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="comments" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 130, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 130, 0) !important"># Calling methods</font></code>
    </div>
    <div class="line number31 index30 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">gfg.g1</font></code>
    </div>
    <div class="line number32 index31 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">gfg.g2</font></code>
    </div>
    <div class="line number33 index32 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">gfg.gfg1</font></code>
    </div>
    <div class="line number34 index33 alt1" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">gfg.gfg2</font></code>
    </div>
    <div class="line number35 index34 alt2" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-right: 0; padding-bottom: 0px; padding-left: 0px; font-size: var(--font-din); vertical-align: baseline !important; background-position: 0px 0px; background-color: rgb(255, 255, 255); background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace; font-weight: 400; font-style: normal; white-space: pre !important; color: rgb(64, 66, 78); letter-spacing: 0.162px; text-indent: 0px; text-transform: none; word-spacing: 0px">
      <code class="plain" style="margin-top: 0px; margin-bottom: 0px; margin-right: 0; margin-left: 0; padding-top: 0px; padding-bottom: 0px; padding-right: 0; padding-left: 0; font-size: 11pt !important; vertical-align: baseline !important; background-position: 0px 0px; background-image: null; background-repeat: repeat; background-attachment: scroll; float: none !important; line-height: 1.2em !important; text-align: left !important; font-family: Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important; font-weight: normal; font-style: normal !important; display: inline !important; color: rgb(0, 0, 0) !important"><font size="11pt !important" face="Consolas, Bitstream Vera Sans Mono, Courier New, Courier, monospace !important" color="rgb(0, 0, 0) !important">gfg.s1</font></code>
    </div>
  </body>
</html></richcontent>
</node>
</node>
</map>
